const fs = require('fs');
const path = require('path');

const graphPath = path.join(__dirname, '../dashboard/src/graph.json');

// Read and fix PowerShell encoding
let rawData = fs.readFileSync(graphPath, 'utf8');
if (rawData.charCodeAt(0) === 0xFEFF) rawData = rawData.slice(1);

try {
    const data = JSON.parse(rawData);

    function getImpact(fileName) {
        const affected = new Set();
        function trace(target) {
            data.modules.forEach(m => {
                // Check if this module depends on the target
                if (m.dependencies.some(d => d.resolved === target) && !affected.has(m.source)) {
                    affected.add(m.source);
                    trace(m.source); // Recurse
                }
            });
        }
        trace(fileName);
        return Array.from(affected);
    }

    // Match the exact path generated by dependency-cruiser
    const fileChanged = "src/database.js"; 
    const impact = getImpact(fileChanged);

    console.log(`--- SnapDiff Impact Report ---`);
    console.log(`If you change: ${fileChanged}`);
    console.log(`You must test:`, impact.length > 0 ? impact : "No downstream dependencies found.");
    
} catch (e) {
    console.error("Error parsing JSON. Try regenerating graph.json.");
}